### PR TITLE
Move up enabled repos check

### LINKED ISSUE #7: Error running the latest flood.py script
with latest master, I get an error running this command:
```sh
# python flood.py      --image ch-d      --satellite satellite.lab.example.com      --name sharad     --key rhel7ak      --count 2      --exit-criteria register
Starting content host creation with criteria reg.
Created: 1
Created: 2
```
The above command was running forever.  While looking at at the logs for one of the docker hosts, I see:

```sh Adding satellite certificate http://satellite.lab.example.com/pub/katello-ca-consumer-latest.noarch.rpm
Retrieving http://satellite.lab.example.com/pub/katello-ca-consumer-latest.noarch.rpm
Preparing...                          ########################################
Updating / installing...
Activation key rhel7ak specified. Registering...
Validation failed: Host has already been taken
Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 To enable Red Hat Subscription Management repositories:
     subscription-manager repos --enable <repo>
 To enable custom repositories:
     yum-config-manager --enable <repo>
Tailing rhsm log.
2018-03-08 21:58:21,577 [INFO] yum:86:MainThread @connection.py:821 - Connection built: host=vms1.mmx.gss.redhat.com port=443 handler=/rhsm auth=identity_cert ca_dir=/etc/rhsm/ca/ insecure=False
2018-03-08 21:58:21,578 [INFO] yum:86:MainThread @repolib.py:326 - repos updated: Repo updates
Total repo updates: 0
Updated
    <NONE>
Added (new)
    <NONE>
Deleted
    <NONE>
```

I am pretty sure that satellite didnt have duplicate host with this name.

### PR DESCRIPTION
**Pull request by JacobCallahan**
This will not only catch if the registration was successful, and
there are no subscription; but will also catch if there is an error
during the registration step.

Fixes #7

### CODE REVIEW

**Comment by sthirugn** [comment]
This will hide the error in https://github.com/JacobCallahan/content-host-d/issues/7 and the user wont know it failed, is there a way to indicate that this container errored so the user can debug further?  Also is there a way to capture /etc/rhsm/rhsm.log from the container and store it locally to debug?

**Comment by JacobCallahan** [comment]
i can print out a message when that condition is met, to provide a bit of feedback.
You should be able to mount the rhsm.log to a local file, but that currently isn't supported by the script.
The docker command should look like:
```
docker run ... -v $(pwd)/local.log:/etc/rhsm/rhsm.log ... ch-d:rhel7
```

**Comment by sthirugn** [comment]
ack, an error message is good to debug further

**Comment by JacobCallahan** [comment]
@sthirugn my satellite was reclaimed, so i can't test positive registrations. However, failed registrations look like this.
```
# python flood.py -s cloud-qe-04.idmqe.lab.eng.bos.redhat.com
Starting content host creation with criteria reg.
Created: 1
Created: 2
Created: 3
Created: 4
Created: 5
Created: 6
Created: 7
Created: 8
Created: 9
Created: 10
Done with 1: No repos enabled. Check registration/subscription status.
Done with 2: No repos enabled. Check registration/subscription status.
Done with 3: No repos enabled. Check registration/subscription status.
Done with 4: No repos enabled. Check registration/subscription status.
Done with 5: No repos enabled. Check registration/subscription status.
Done with 6: No repos enabled. Check registration/subscription status.
Done with 7: No repos enabled. Check registration/subscription status.
Done with 8: No repos enabled. Check registration/subscription status.
Done with 9: No repos enabled. Check registration/subscription status.
Done with 10: No repos enabled. Check registration/subscription status.
Finished content host creation.
```
Also, I added a new parameter to the host deletion that will let us set any exit message we want. Default is 'Success'

**Comment by sthirugn** [comment]
Great, created an issue https://github.com/JacobCallahan/content-host-d/issues/9 to enable logging.

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
