### PR TITLE
Updated chdir argument of command module

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Comment by sthirugn** [comment]
After this PR merge, we will have solid set of logs to troubleshoot containers. Also see https://github.com/SatelliteQE/robottelo-ci/pull/1060

**Comment by JacobCallahan** [comment]
Interesting. How does this work? Just curious, won't block.

**Comment by sthirugn** [comment]
`chdir` is an argument to the `command` module.  The `command` module first changes the working directory to the provided directory and then runs the supplied command.

**Comment by JacobCallahan** [comment]
Thanks for the info, and PR! ACK

**Pull request merged**
